# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘3.0’ # or '3.0'
    end
  end
end




target 'FoodCR2' do

 use_frameworks!
  pod "DCCoreDataManager"
  pod "Alamofire"
  pod "AlamofireObjectMapper"
  pod “RealmSwift”
end
